name: File Operations on Desktop

on:
  workflow_dispatch: # Manual trigger from GitHub UI

jobs:
  file-work:
    runs-on: self-hosted  # Your Windows runner

    steps:
      - name: Create folder1 on Desktop
        run: |
          $desktop = [Environment]::GetFolderPath("Desktop")
          New-Item -Path "$desktop\folder1" -ItemType Directory

      - name: Create 1.txt inside folder1
        run: |
          $desktop = [Environment]::GetFolderPath("Desktop")
          Set-Content -Path "$desktop\folder1\1.txt" -Value "This is file 1"

      - name: Create folder2 on Desktop
        run: |
          $desktop = [Environment]::GetFolderPath("Desktop")
          New-Item -Path "$desktop\folder2" -ItemType Directory

      - name: Copy 1.txt from folder1 to folder2
        run: |
          $desktop = [Environment]::GetFolderPath("Desktop")
          Copy-Item -Path "$desktop\folder1\1.txt" -Destination "$desktop\folder2"
