name: File Operations on Desktop

on:
  workflow_dispatch: # Trigger manually from GitHub UI

jobs:
  file-work:
    runs-on: self-hosted  # Run on your laptop

    steps:
      - name: Create folders and file on Desktop
        run: |
          $desktopPath = "C:\Users\Administrator\Desktop"
          $folder1 = "$desktopPath\folder1"
          $folder2 = "$desktopPath\folder2"

          # Create folder1 if it doesn't exist
          if (!(Test-Path $folder1)) {
            New-Item -Path $folder1 -ItemType Directory
          }

          # Create file 1.txt inside folder1
          Set-Content -Path "$folder1\1.txt" -Value "This is file 1"

          # Create folder2 if it doesn't exist
          if (!(Test-Path $folder2)) {
            New-Item -Path $folder2 -ItemType Directory
          }

          # Copy file from folder1 to folder2
          Copy-Item -Path "$folder1\1.txt" -Destination $folder2
